using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace PortfolioTracker.Data.Migrations
{
    /// <inheritdoc />
    public partial class AssetInstrumentTradingDataEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Instruments",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    InsCode = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    Ticker = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    Board = table.Column<int>(type: "int", nullable: true),
                    Industry = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Instruments", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Assets",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    InstrumentId = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    Quantity = table.Column<long>(type: "bigint", nullable: false),
                    AveragePrice = table.Column<decimal>(type: "decimal(18,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Assets", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Assets_Instruments_InstrumentId",
                        column: x => x.InstrumentId,
                        principalTable: "Instruments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TradingData",
                columns: table => new
                {
                    InstrumentId = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    Date = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: true),
                    OpeningPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    HighestPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LowestPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LastPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ClosingPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PreviousClosingPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UpperBoundPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LowerBoundPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NumberOfTrades = table.Column<int>(type: "int", nullable: true),
                    TradingValue = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TradingVolume = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TradingData", x => new { x.InstrumentId, x.Date });
                    table.ForeignKey(
                        name: "FK_TradingData_Instruments_InstrumentId",
                        column: x => x.InstrumentId,
                        principalTable: "Instruments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Instruments",
                columns: new[] { "Id", "Board", "Industry", "InsCode", "Name", "Ticker" },
                values: new object[,]
                {
                    { "IRO1ABAD0001", null, null, null, null, "ثاباد1" },
                    { "IRO1ABDI0001", null, null, null, null, "دعبيد1" },
                    { "IRO1ABIK0001", null, null, null, null, "سابيك1" },
                    { "IRO1ALBZ0001", null, null, null, null, "والبر1" },
                    { "IRO1ALIR0001", null, null, null, null, "فايرا1" },
                    { "IRO1ALMR0001", null, null, null, null, "فمراد1" },
                    { "IRO1ALVN0001", null, null, null, null, "كلوند1" },
                    { "IRO1AMIN0001", null, null, null, null, "دامين1" },
                    { "IRO1AMLH0001", null, null, null, null, "شاملا1" },
                    { "IRO1APPE0001", null, null, null, null, "آپ1" },
                    { "IRO1ARDK0001", null, null, null, null, "كسرا1" },
                    { "IRO1ASAL0001", null, null, null, null, "لابسا1" },
                    { "IRO1ASIA0001", null, null, null, null, "آسيا1" },
                    { "IRO1ASTC0001", null, null, null, null, "آسياتك1" },
                    { "IRO1ATDM0001", null, null, null, null, "واتي1" },
                    { "IRO1ATIR0001", null, null, null, null, "خاهن1" },
                    { "IRO1AYEG0001", null, null, null, null, "پرديس1" },
                    { "IRO1AZAB0001", null, null, null, null, "فاذر1" },
                    { "IRO1AZIN0001", null, null, null, null, "خاذين1" },
                    { "IRO1BAFG0001", null, null, null, null, "كبافق1" },
                    { "IRO1BAHN0001", null, null, null, null, "فباهنر1" },
                    { "IRO1BALB0001", null, null, null, null, "البرز1" },
                    { "IRO1BALI0001", null, null, null, null, "وبوعلي1" },
                    { "IRO1BAMA0001", null, null, null, null, "كاما1" },
                    { "IRO1BANK0001", null, null, null, null, "وبانك1" },
                    { "IRO1BANS0001", null, null, null, null, "وانصار1" },
                    { "IRO1BARZ0001", null, null, null, null, "پكرمان1" },
                    { "IRO1BDAN0001", null, null, null, null, "دانا1" },
                    { "IRO1BEKA0001", null, null, null, null, "ثبهساز1" },
                    { "IRO1BENA0001", null, null, null, null, "انرژي11" },
                    { "IRO1BENB0001", null, null, null, null, "انرژي21" },
                    { "IRO1BENC0001", null, null, null, null, "انرژي31" },
                    { "IRO1BENN0001", null, null, null, null, "غبهنوش1" },
                    { "IRO1BFJR0001", null, null, null, null, "بفجر1" },
                    { "IRO1BHMN0001", null, null, null, null, "خبهمن1" },
                    { "IRO1BIME0001", null, null, null, null, "وبيمه1" },
                    { "IRO1BKHZ0001", null, null, null, null, "وخاور1" },
                    { "IRO1BKLA0001", null, null, null, null, "اكالا1" },
                    { "IRO1BMEL0001", null, null, null, null, "ملت1" },
                    { "IRO1BMLI0001", null, null, null, null, "ثملي1" },
                    { "IRO1BMLT0001", null, null, null, null, "وبملت1" },
                    { "IRO1BMPS0001", null, null, null, null, "شپارس1" },
                    { "IRO1BONA0001", null, null, null, null, "بوعلي1" },
                    { "IRO1BORS0001", null, null, null, null, "بورس1" },
                    { "IRO1BOTA0001", null, null, null, null, "لبوتان1" },
                    { "IRO1BPAR0001", null, null, null, null, "وپارس1" },
                    { "IRO1BPAS0001", null, null, null, null, "وپاسار1" },
                    { "IRO1BPST0001", null, null, null, null, "وپست1" },
                    { "IRO1BRKT0001", null, null, null, null, "بركت1" },
                    { "IRO1BSDR0001", null, null, null, null, "وبصادر1" },
                    { "IRO1BSTE0001", null, null, null, null, "ثاخت1" },
                    { "IRO1BTEJ0001", null, null, null, null, "وتجارت1" },
                    { "IRO1BVMA0001", null, null, null, null, "ما1" },
                    { "IRO1CHAR0001", null, null, null, null, "خچرخش1" },
                    { "IRO1CHCH0001", null, null, null, null, "غچين1" },
                    { "IRO1CHDN0001", null, null, null, null, "چدن1" },
                    { "IRO1CHML0001", null, null, null, null, "كچاد1" },
                    { "IRO1CIDC0001", null, null, null, null, "سيدكو1" },
                    { "IRO1COMB0001", null, null, null, null, "تكمبا1" },
                    { "IRO1CONT0001", null, null, null, null, "آكنتور1" },
                    { "IRO1CRBN0001", null, null, null, null, "شكربن1" },
                    { "IRO1DABO0001", null, null, null, null, "دابور1" },
                    { "IRO1DADE0001", null, null, null, null, "مداران1" },
                    { "IRO1DALZ0001", null, null, null, null, "دالبر1" },
                    { "IRO1DAML0001", null, null, null, null, "ددام1" },
                    { "IRO1DARO0001", null, null, null, null, "وپخش1" },
                    { "IRO1DDPK0001", null, null, null, null, "دشيمي1" },
                    { "IRO1DFRB0001", null, null, null, null, "دفارا1" },
                    { "IRO1DJBR0001", null, null, null, null, "دجابر1" },
                    { "IRO1DKSR0001", null, null, null, null, "دكوثر1" },
                    { "IRO1DLGM0001", null, null, null, null, "دلقما1" },
                    { "IRO1DMOR0001", null, null, null, null, "غدشت1" },
                    { "IRO1DMVN0001", null, null, null, null, "كدما1" },
                    { "IRO1DODE0001", null, null, null, null, "شدوص1" },
                    { "IRO1DOSE0001", null, null, null, null, "داسوه1" },
                    { "IRO1DPAK0001", null, null, null, null, "دارو1" },
                    { "IRO1DRKH0001", null, null, null, null, "پدرخش1" },
                    { "IRO1DRZK0001", null, null, null, null, "درازك1" },
                    { "IRO1DSBH0001", null, null, null, null, "دسبحان1" },
                    { "IRO1DSIN0001", null, null, null, null, "دسينا1" },
                    { "IRO1DSOB0001", null, null, null, null, "دسبحا1" },
                    { "IRO1DTIP0001", null, null, null, null, "تيپيكو1" },
                    { "IRO1DZAH0001", null, null, null, null, "دزهراوي1" },
                    { "IRO1EPRS0001", null, null, null, null, "رتاپ1" },
                    { "IRO1EXIR0001", null, null, null, null, "دلر1" },
                    { "IRO1FAIR0001", null, null, null, null, "فولاژ1" },
                    { "IRO1FAJR0001", null, null, null, null, "فجر1" },
                    { "IRO1FIBR0001", null, null, null, null, "چفيبر1" },
                    { "IRO1FKAS0001", null, null, null, null, "فخاس1" },
                    { "IRO1FKHZ0001", null, null, null, null, "فخوز1" },
                    { "IRO1FNAR0001", null, null, null, null, "خزر1" },
                    { "IRO1FOLD0001", null, null, null, null, "فولاد1" },
                    { "IRO1FRIS0001", null, null, null, null, "فروس1" },
                    { "IRO1FRVR0001", null, null, null, null, "فرآور1" },
                    { "IRO1FSAZ0001", null, null, null, null, "فسازان1" },
                    { "IRO1FSIN0001", null, null, null, null, "سينا1" },
                    { "IRO1FTIR0001", null, null, null, null, "دفرا1" },
                    { "IRO1GARN0001", null, null, null, null, "قرن1" },
                    { "IRO1GBEH0001", null, null, null, null, "وصنا1" },
                    { "IRO1GCOZ0001", null, null, null, null, "غگل1" },
                    { "IRO1GDIR0001", null, null, null, null, "وغدير1" },
                    { "IRO1GESF0001", null, null, null, null, "قصفها1" },
                    { "IRO1GGAZ0001", null, null, null, null, "قزوين1" },
                    { "IRO1GHAT0001", null, null, null, null, "ختوقا1" },
                    { "IRO1GHEG0001", null, null, null, null, "قهكمت1" },
                    { "IRO1GHND0001", null, null, null, null, "قشهد1" },
                    { "IRO1GLOR0001", null, null, null, null, "قلرست1" },
                    { "IRO1GMEL0001", null, null, null, null, "وملي1" },
                    { "IRO1GMRO0001", null, null, null, null, "قمرو1" },
                    { "IRO1GNBO0001", null, null, null, null, "قنيشا1" },
                    { "IRO1GOLG0001", null, null, null, null, "كگل1" },
                    { "IRO1GORJ0001", null, null, null, null, "غگرجي1" },
                    { "IRO1GOST0001", null, null, null, null, "خگستر1" },
                    { "IRO1GPSH0001", null, null, null, null, "قپيرا1" },
                    { "IRO1GSBE0001", null, null, null, null, "قثابت1" },
                    { "IRO1GSKE0001", null, null, null, null, "تكشا1" },
                    { "IRO1GTSH0001", null, null, null, null, "شگل1" },
                    { "IRO1HFRS0001", null, null, null, null, "حفارس1" },
                    { "IRO1HJPT0001", null, null, null, null, "حپترو1" },
                    { "IRO1HMRZ0001", null, null, null, null, "همراه1" },
                    { "IRO1HSHM0001", null, null, null, null, "حفاري1" },
                    { "IRO1HTOK0001", null, null, null, null, "حتوكا1" },
                    { "IRO1HWEB0001", null, null, null, null, "هاي وب1" },
                    { "IRO1IAGM0001", null, null, null, null, "مرقام1" },
                    { "IRO1IDOC0001", null, null, null, null, "واعتبار1" },
                    { "IRO1IKCO0001", null, null, null, null, "خودرو1" },
                    { "IRO1IKHR0001", null, null, null, null, "وخارزم1" },
                    { "IRO1INDM0001", null, null, null, null, "خكمك1" },
                    { "IRO1INFO0001", null, null, null, null, "رانفور1" },
                    { "IRO1IPAR0001", null, null, null, null, "پارسيان1" },
                    { "IRO1IPTR0001", null, null, null, null, "پترول1" },
                    { "IRO1IRDR0001", null, null, null, null, "ديران1" },
                    { "IRO1JAMD0001", null, null, null, null, "فجام1" },
                    { "IRO1JOSH0001", null, null, null, null, "بكاب1" },
                    { "IRO1JPPC0001", null, null, null, null, "جم پيلن1" },
                    { "IRO1KALA0001", null, null, null, null, "كالا1" },
                    { "IRO1KALZ0001", null, null, null, null, "بالبر1" },
                    { "IRO1KAPA0011", null, null, null, null, "چكاپا1" },
                    { "IRO1KBRS0001", null, null, null, null, "كبورس1" },
                    { "IRO1KCHI0001", null, null, null, null, "كخاك1" },
                    { "IRO1KDPS0001", null, null, null, null, "غدام1" },
                    { "IRO1KFAN0001", null, null, null, null, "خفنر1" },
                    { "IRO1KGND0001", null, null, null, null, "بكام1" },
                    { "IRO1KHAZ0001", null, null, null, null, "لخزر1" },
                    { "IRO1KHFZ0001", null, null, null, null, "كحافظ1" },
                    { "IRO1KHOC0001", null, null, null, null, "سخوز1" },
                    { "IRO1KHSH0001", null, null, null, null, "خشرق1" },
                    { "IRO1KIMI0001", null, null, null, null, "دكيمي1" },
                    { "IRO1KLBR0001", null, null, null, null, "غالبر1" },
                    { "IRO1KNRZ0001", null, null, null, null, "كنور1" },
                    { "IRO1KOSR0001", null, null, null, null, "زكوثر1" },
                    { "IRO1KPRS0001", null, null, null, null, "كپارس1" },
                    { "IRO1KRAF0001", null, null, null, null, "وكار1" },
                    { "IRO1KRIR0001", null, null, null, null, "خكار1" },
                    { "IRO1KRSN0001", null, null, null, null, "خراسان1" },
                    { "IRO1KRTI0001", null, null, null, null, "چكارن1" },
                    { "IRO1KSAD0001", null, null, null, null, "كسعدي1" },
                    { "IRO1KSHJ0001", null, null, null, null, "حكشتي1" },
                    { "IRO1KSIM0001", null, null, null, null, "فاسمين1" },
                    { "IRO1KSKA0001", null, null, null, null, "چكاوه1" },
                    { "IRO1KTEK0001", null, null, null, null, "كيمياتك1" },
                    { "IRO1KVEH0001", null, null, null, null, "كاوه1" },
                    { "IRO1KVIR0001", null, null, null, null, "كوير1" },
                    { "IRO1KVRZ0001", null, null, null, null, "پكوير1" },
                    { "IRO1LAMI0001", null, null, null, null, "فلامي1" },
                    { "IRO1LAPS0001", null, null, null, null, "بشهاب1" },
                    { "IRO1LEAB0001", null, null, null, null, "شلعاب1" },
                    { "IRO1LENT0001", null, null, null, null, "خلنت1" },
                    { "IRO1LIRZ0001", null, null, null, null, "وايران1" },
                    { "IRO1LKAR0001", null, null, null, null, "ولكار1" },
                    { "IRO1LKGH0001", null, null, null, null, "ولغدر1" },
                    { "IRO1LMIR0001", null, null, null, null, "فلوله1" },
                    { "IRO1LPAK0001", null, null, null, null, "غپاك1" },
                    { "IRO1LPRS0001", null, null, null, null, "ولپارس1" },
                    { "IRO1LSMD0001", null, null, null, null, "ولصنم1" },
                    { "IRO1LTOS0001", null, null, null, null, "لوتوس1" },
                    { "IRO1LZIN0001", null, null, null, null, "وليز1" },
                    { "IRO1MADN0001", null, null, null, null, "ومعادن1" },
                    { "IRO1MAGS0001", null, null, null, null, "زمگسا1" },
                    { "IRO1MAPN0001", null, null, null, null, "رمپنا1" },
                    { "IRO1MARK0001", null, null, null, null, "فاراك1" },
                    { "IRO1MESI0001", null, null, null, null, "خوساز1" },
                    { "IRO1MHKM0001", null, null, null, null, "خمهر1" },
                    { "IRO1MINO0001", null, null, null, null, "غپينو1" },
                    { "IRO1MKBT0001", null, null, null, null, "اخابر1" },
                    { "IRO1MNGZ0001", null, null, null, null, "كمنگنز1" },
                    { "IRO1MNSR0001", null, null, null, null, "خنصير1" },
                    { "IRO1MOBN0001", null, null, null, null, "مبين1" },
                    { "IRO1MOIN0001", null, null, null, null, "ومعين1" },
                    { "IRO1MOTJ0001", null, null, null, null, "بموتو1" },
                    { "IRO1MRAM0001", null, null, null, null, "غمهرا1" },
                    { "IRO1MRGN0001", null, null, null, null, "غمارگ1" },
                    { "IRO1MRIN0001", null, null, null, null, "نمرينو1" },
                    { "IRO1MSKN0001", null, null, null, null, "ثمسكن1" },
                    { "IRO1MSMI0001", null, null, null, null, "فملي1" },
                    { "IRO1MSTI0001", null, null, null, null, "خموتور1" },
                    { "IRO1NAFT0001", null, null, null, null, "ونفت1" },
                    { "IRO1NALM0001", null, null, null, null, "فنوال1" },
                    { "IRO1NASI0001", null, null, null, null, "كفرا1" },
                    { "IRO1NBAB0001", null, null, null, null, "آبادا1" },
                    { "IRO1NBEH0001", null, null, null, null, "شبهرن1" },
                    { "IRO1NBRS0001", null, null, null, null, "نبورس1" },
                    { "IRO1NGFO0001", null, null, null, null, "فنورد1" },
                    { "IRO1NIKI0001", null, null, null, null, "ونيكي1" },
                    { "IRO1NIRO0001", null, null, null, null, "بنيرو1" },
                    { "IRO1NJEY0001", null, null, null, null, "شجي1" },
                    { "IRO1NKLA0001", null, null, null, null, "نكالا1" },
                    { "IRO1NKOL0001", null, null, null, null, "شكلر1" },
                    { "IRO1NMOH0001", null, null, null, null, "خمحركه1" },
                    { "IRO1NORI0001", null, null, null, null, "نوري1" },
                    { "IRO1NOSH0001", null, null, null, null, "غنوش1" },
                    { "IRO1NOVN0001", null, null, null, null, "ونوين1" },
                    { "IRO1NPRS0001", null, null, null, null, "شنفت1" },
                    { "IRO1NSAZ0001", null, null, null, null, "كاذر1" },
                    { "IRO1NSPS0001", null, null, null, null, "كفپارس1" },
                    { "IRO1NSTH0001", null, null, null, null, "ثنوسا1" },
                    { "IRO1OFOG0001", null, null, null, null, "افق1" },
                    { "IRO1OFRS0001", null, null, null, null, "ثفارس1" },
                    { "IRO1OFST0001", null, null, null, null, "چافست1" },
                    { "IRO1OIMC0001", null, null, null, null, "واميد1" },
                    { "IRO1OMID0001", null, null, null, null, "اميد1" },
                    { "IRO1OS010001", null, null, null, null, "وساشرقي1" },
                    { "IRO1OS020001", null, null, null, null, "وساغربي1" },
                    { "IRO1OS030001", null, null, null, null, "وساربيل1" },
                    { "IRO1OS040001", null, null, null, null, "وسصفا1" },
                    { "IRO1OS050001", null, null, null, null, "وسيلام1" },
                    { "IRO1OS060001", null, null, null, null, "وسبوشهر1" },
                    { "IRO1OS080001", null, null, null, null, "وسمحال1" },
                    { "IRO1OS090001", null, null, null, null, "وسخراج1" },
                    { "IRO1OS100001", null, null, null, null, "وسرضوي1" },
                    { "IRO1OS110001", null, null, null, null, "وسخراش1" },
                    { "IRO1OS120001", null, null, null, null, "وسخوز1" },
                    { "IRO1OS130001", null, null, null, null, "وسزنجان1" },
                    { "IRO1OS150001", null, null, null, null, "وسيستا1" },
                    { "IRO1OS160001", null, null, null, null, "وسفارس1" },
                    { "IRO1OS180001", null, null, null, null, "وسقم1" },
                    { "IRO1OS190001", null, null, null, null, "وسكرد1" },
                    { "IRO1OS200001", null, null, null, null, "وسكرمان1" },
                    { "IRO1OS210001", null, null, null, null, "وسكرشا1" },
                    { "IRO1OS220001", null, null, null, null, "وسكهبو1" },
                    { "IRO1OS230001", null, null, null, null, "وسگلستا1" },
                    { "IRO1OS240001", null, null, null, null, "وسگيلا1" },
                    { "IRO1OS250001", null, null, null, null, "وسلرستا1" },
                    { "IRO1OS260001", null, null, null, null, "وسمازن1" },
                    { "IRO1OS270001", null, null, null, null, "وسمركز1" },
                    { "IRO1OS280001", null, null, null, null, "وسهرمز1" },
                    { "IRO1OS290001", null, null, null, null, "وسهمدا1" },
                    { "IRO1OS300001", null, null, null, null, "وسيزد1" },
                    { "IRO1PAKS0001", null, null, null, null, "شپاكسا1" },
                    { "IRO1PARK0001", null, null, null, null, "شاراك1" },
                    { "IRO1PARS0001", null, null, null, null, "پارس1" },
                    { "IRO1PASH0001", null, null, null, null, "پاكشو1" },
                    { "IRO1PASN0001", null, null, null, null, "پارسان1" },
                    { "IRO1PDRO0001", null, null, null, null, "دپارس1" },
                    { "IRO1PELC0001", null, null, null, null, "لپارس1" },
                    { "IRO1PERS0001", null, null, null, null, "پرشيا1" },
                    { "IRO1PETR0001", null, null, null, null, "وپترو1" },
                    { "IRO1PFAN0001", null, null, null, null, "شفن1" },
                    { "IRO1PIAZ0001", null, null, null, null, "غاذر1" },
                    { "IRO1PIRN0001", null, null, null, null, "تپمپي1" },
                    { "IRO1PJMZ0001", null, null, null, null, "جم1" },
                    { "IRO1PKER0001", null, null, null, null, "كرماشا1" },
                    { "IRO1PKHA0001", null, null, null, null, "شخارك1" },
                    { "IRO1PKLJ0001", null, null, null, null, "فارس1" },
                    { "IRO1PKOD0001", null, null, null, null, "خپارس1" },
                    { "IRO1PLKK0001", null, null, null, null, "پلاسك1" },
                    { "IRO1PMSZ0001", null, null, null, null, "ثشرق1" },
                    { "IRO1PNBA0001", null, null, null, null, "شبندر1" },
                    { "IRO1PNES0001", null, null, null, null, "شپنا1" },
                    { "IRO1PNTB0001", null, null, null, null, "شبريز1" },
                    { "IRO1PRDZ0001", null, null, null, null, "شپديس1" },
                    { "IRO1PRKT0001", null, null, null, null, "پرداخت1" },
                    { "IRO1PSER0001", null, null, null, null, "كسرام1" },
                    { "IRO1PSHZ0001", null, null, null, null, "شيراز1" },
                    { "IRO1PSIR0001", null, null, null, null, "كپشير1" },
                    { "IRO1PTAP0001", null, null, null, null, "تاپيكو1" },
                    { "IRO1PTEH0001", null, null, null, null, "شتران1" },
                    { "IRO1RADI0001", null, null, null, null, "ختور1" },
                    { "IRO1RENA0001", null, null, null, null, "ورنا1" },
                    { "IRO1RIIR0001", null, null, null, null, "خريخت1" },
                    { "IRO1RINM0001", null, null, null, null, "خرينگ1" },
                    { "IRO1RKSH0001", null, null, null, null, "ركيش1" },
                    { "IRO1ROOI0001", null, null, null, null, "كروي1" },
                    { "IRO1ROZD0001", null, null, null, null, "دروز1" },
                    { "IRO1RSAP0001", null, null, null, null, "ولساپا1" },
                    { "IRO1RTIR0001", null, null, null, null, "ختراك1" },
                    { "IRO1RVND0001", null, null, null, null, "اروند1" },
                    { "IRO1SADB0001", null, null, null, null, "ساربيل1" },
                    { "IRO1SADR0001", null, null, null, null, "تاصيكو1" },
                    { "IRO1SAHD0001", null, null, null, null, "ثشاهد1" },
                    { "IRO1SAKH0001", null, null, null, null, "وساخت1" },
                    { "IRO1SAMA0001", null, null, null, null, "فاما1" },
                    { "IRO1SAND0001", null, null, null, null, "وصندوق1" },
                    { "IRO1SBAH0001", null, null, null, null, "وبهمن1" },
                    { "IRO1SBEH0001", null, null, null, null, "غبشهر1" },
                    { "IRO1SBHN0001", null, null, null, null, "سبهان1" },
                    { "IRO1SBOJ0001", null, null, null, null, "سبجنو1" },
                    { "IRO1SDAB0001", null, null, null, null, "ساراب1" },
                    { "IRO1SDOR0001", null, null, null, null, "سدور1" },
                    { "IRO1SDST0001", null, null, null, null, "سدشت1" },
                    { "IRO1SEFH0001", null, null, null, null, "سصفها1" },
                    { "IRO1SEIL0001", null, null, null, null, "سيلام1" },
                    { "IRO1SEPA0001", null, null, null, null, "فسپا1" },
                    { "IRO1SEPK0001", null, null, null, null, "سپ1" },
                    { "IRO1SEPP0001", null, null, null, null, "شسپا1" },
                    { "IRO1SFKZ0001", null, null, null, null, "سفارس1" },
                    { "IRO1SFNO0001", null, null, null, null, "سفانو1" },
                    { "IRO1SFRS0001", null, null, null, null, "سفار1" },
                    { "IRO1SGAZ0001", null, null, null, null, "كگاز1" },
                    { "IRO1SGEN0001", null, null, null, null, "سقاين1" },
                    { "IRO1SGOS0001", null, null, null, null, "ثامان1" },
                    { "IRO1SGRB0001", null, null, null, null, "سغرب1" },
                    { "IRO1SHAD0001", null, null, null, null, "غشهد1" },
                    { "IRO1SHFA0001", null, null, null, null, "شفا1" },
                    { "IRO1SHFS0001", null, null, null, null, "شفارس1" },
                    { "IRO1SHGN0001", null, null, null, null, "سهگمت1" },
                    { "IRO1SHKR0001", null, null, null, null, "قشكر1" },
                    { "IRO1SHMD0001", null, null, null, null, "كهمدا1" },
                    { "IRO1SHND0001", null, null, null, null, "پسهند1" },
                    { "IRO1SHOY0001", null, null, null, null, "شوينده1" },
                    { "IRO1SHPZ0001", null, null, null, null, "غشاذر1" },
                    { "IRO1SHSI0001", null, null, null, null, "شسينا1" },
                    { "IRO1SHZG0001", null, null, null, null, "سهرمز1" },
                    { "IRO1SIMS0001", null, null, null, null, "سشمال1" },
                    { "IRO1SINA0001", null, null, null, null, "كساوه1" },
                    { "IRO1SIPA0001", null, null, null, null, "خساپا1" },
                    { "IRO1SISH0001", null, null, null, null, "كساپا1" },
                    { "IRO1SITA0001", null, null, null, null, "سيتا1" },
                    { "IRO1SKAZ0001", null, null, null, null, "سخزر1" },
                    { "IRO1SKBV0001", null, null, null, null, "وسكاب1" },
                    { "IRO1SKER0001", null, null, null, null, "سكرما1" },
                    { "IRO1SKHS0001", null, null, null, null, "سخاش1" },
                    { "IRO1SKOR0001", null, null, null, null, "سكرد1" },
                    { "IRO1SLMN0001", null, null, null, null, "غسالم1" },
                    { "IRO1SMAZ0001", null, null, null, null, "سمازن1" },
                    { "IRO1SMRG0001", null, null, null, null, "سيمرغ1" },
                    { "IRO1SNMA0001", null, null, null, null, "وصنعت1" },
                    { "IRO1SNRO0001", null, null, null, null, "ونيرو1" },
                    { "IRO1SORB0001", null, null, null, null, "فسرب1" },
                    { "IRO1SPAH0001", null, null, null, null, "وسپه1" },
                    { "IRO1SPID0001", null, null, null, null, "سپيد1" },
                    { "IRO1SPKH0001", null, null, null, null, "غشان1" },
                    { "IRO1SPPE0001", null, null, null, null, "غشصفا1" },
                    { "IRO1SPTA0001", null, null, null, null, "فپنتا1" },
                    { "IRO1SRMA0001", null, null, null, null, "لسرما1" },
                    { "IRO1SROD0001", null, null, null, null, "سرود1" },
                    { "IRO1SSAP0001", null, null, null, null, "وساپا1" },
                    { "IRO1SSEP0001", null, null, null, null, "سپاها1" },
                    { "IRO1SSHR0001", null, null, null, null, "سشرق1" },
                    { "IRO1SSIN0001", null, null, null, null, "شيران1" },
                    { "IRO1SSNR0001", null, null, null, null, "سنير1" },
                    { "IRO1SSOF0001", null, null, null, null, "سصوفي1" },
                    { "IRO1STEH0001", null, null, null, null, "ستران1" },
                    { "IRO1SURO0001", null, null, null, null, "ساروم1" },
                    { "IRO1SWIC0001", null, null, null, null, "بسويچ1" },
                    { "IRO1SYSM0001", null, null, null, null, "سيستم1" },
                    { "IRO1SZPO0001", null, null, null, null, "خپويش1" },
                    { "IRO1TAIR0001", null, null, null, null, "پتاير1" },
                    { "IRO1TAMI0001", null, null, null, null, "كماسه1" },
                    { "IRO1TAYD0001", null, null, null, null, "حتايد1" },
                    { "IRO1TAZB0001", null, null, null, null, "وآذر1" },
                    { "IRO1TBAS0001", null, null, null, null, "كطبس1" },
                    { "IRO1TGOS0001", null, null, null, null, "وتوس1" },
                    { "IRO1TKIN0001", null, null, null, null, "رتكو1" },
                    { "IRO1TKLA0001", null, null, null, null, "تكالا1" },
                    { "IRO1TKNO0001", null, null, null, null, "تكنو1" },
                    { "IRO1TKSM0001", null, null, null, null, "كترام1" },
                    { "IRO1TMDN0001", null, null, null, null, "تمدن1" },
                    { "IRO1TMEL0001", null, null, null, null, "وتوسم1" },
                    { "IRO1TMKH0001", null, null, null, null, "خمحور1" },
                    { "IRO1TMLT0001", null, null, null, null, "تملت1" },
                    { "IRO1TMVD0001", null, null, null, null, "دتماد1" },
                    { "IRO1TNOV0001", null, null, null, null, "تنوين1" },
                    { "IRO1TOKA0001", null, null, null, null, "وتوكا1" },
                    { "IRO1TOOM0001", null, null, null, null, "ثاميد1" },
                    { "IRO1TOSA0001", null, null, null, null, "وتوصا1" },
                    { "IRO1TRIR0001", null, null, null, null, "تايرا1" },
                    { "IRO1TRNS0001", null, null, null, null, "بترانس1" },
                    { "IRO1TSAN0001", null, null, null, null, "امين1" },
                    { "IRO1TSBE0001", null, null, null, null, "وبشهر1" },
                    { "IRO1TSHE0001", null, null, null, null, "وتوشه1" },
                    { "IRO1TSRZ0001", null, null, null, null, "كرازي1" },
                    { "IRO1TTZC0001", null, null, null, null, "برانسفو1" },
                    { "IRO1VALE0001", null, null, null, null, "ولنوين1" },
                    { "IRO1VLMT0001", null, null, null, null, "ولملت1" },
                    { "IRO1VMDR0001", null, null, null, null, "ومدير1" },
                    { "IRO1VSIN0001", null, null, null, null, "وسينا1" },
                    { "IRO1YASA0001", null, null, null, null, "پاسا1" },
                    { "IRO1ZARM0001", null, null, null, null, "غزر1" },
                    { "IRO1ZBAL0001", null, null, null, null, "اجداد1" },
                    { "IRO1ZMYD0001", null, null, null, null, "خزاميا1" },
                    { "IRO1ZPRS0001", null, null, null, null, "زپارس1" },
                    { "IRR1ABAD0101", null, null, null, null, "ثابادح1" },
                    { "IRR1ALBZ0101", null, null, null, null, "والبرح1" },
                    { "IRR1ALIR0101", null, null, null, null, "فايراح1" },
                    { "IRR1ALMR0101", null, null, null, null, "فمرادح1" },
                    { "IRR1ALVN0101", null, null, null, null, "كلوندح1" },
                    { "IRR1AMIN0101", null, null, null, null, "دامينح1" },
                    { "IRR1ARDK0101", null, null, null, null, "كسراح1" },
                    { "IRR1ASAL0101", null, null, null, null, "لابساح1" },
                    { "IRR1ATDM0101", null, null, null, null, "واتيح1" },
                    { "IRR1ATIR0101", null, null, null, null, "خاهنح1" },
                    { "IRR1AYEG0101", null, null, null, null, "پرديسح1" },
                    { "IRR1AZAB0101", null, null, null, null, "فاذرح1" },
                    { "IRR1AZIN0101", null, null, null, null, "خاذينح1" },
                    { "IRR1BAFG0101", null, null, null, null, "كبافقح1" },
                    { "IRR1BAHN0101", null, null, null, null, "فباهنرح1" },
                    { "IRR1BALB0101", null, null, null, null, "البرزح1" },
                    { "IRR1BALI0101", null, null, null, null, "وبوعليح1" },
                    { "IRR1BAMA0101", null, null, null, null, "كاماح1" },
                    { "IRR1BANK0101", null, null, null, null, "وبانكح1" },
                    { "IRR1BANS0101", null, null, null, null, "وانصارح1" },
                    { "IRR1BARZ0101", null, null, null, null, "پكرمانح1" },
                    { "IRR1BDAN0101", null, null, null, null, "داناح1" },
                    { "IRR1BENN0101", null, null, null, null, "غبهنوشح1" },
                    { "IRR1BHMN0101", null, null, null, null, "خبهمنح1" },
                    { "IRR1BIME0101", null, null, null, null, "وبيمهح1" },
                    { "IRR1BKHZ0101", null, null, null, null, "وخاورح1" },
                    { "IRR1BMEL0101", null, null, null, null, "ملتح1" },
                    { "IRR1BMLT0101", null, null, null, null, "وبملتح1" },
                    { "IRR1BOTA0101", null, null, null, null, "لبوتانح1" },
                    { "IRR1BPAR0101", null, null, null, null, "وپارسح1" },
                    { "IRR1BPAS0101", null, null, null, null, "وپاسارح1" },
                    { "IRR1BRKT0101", null, null, null, null, "بركتح1" },
                    { "IRR1BSTE0101", null, null, null, null, "ثاختح1" },
                    { "IRR1BTEJ0101", null, null, null, null, "وتجارتح1" },
                    { "IRR1BVMA0101", null, null, null, null, "ماح1" },
                    { "IRR1CHAR0101", null, null, null, null, "خچرخشح1" },
                    { "IRR1CHCH0101", null, null, null, null, "غچينح1" },
                    { "IRR1CIDC0101", null, null, null, null, "سيدكوح1" },
                    { "IRR1COMB0101", null, null, null, null, "تكمباح1" },
                    { "IRR1CONT0101", null, null, null, null, "آكنتورح1" },
                    { "IRR1CRBN0101", null, null, null, null, "شكربنح1" },
                    { "IRR1DADE0101", null, null, null, null, "مدارانح1" },
                    { "IRR1DALZ0101", null, null, null, null, "دالبرح1" },
                    { "IRR1DAML0101", null, null, null, null, "ددامح1" },
                    { "IRR1DARO0101", null, null, null, null, "وپخشح1" },
                    { "IRR1DDPK0101", null, null, null, null, "دشيميح1" },
                    { "IRR1DFRB0101", null, null, null, null, "دفاراح1" },
                    { "IRR1DJBR0101", null, null, null, null, "دجابرح1" },
                    { "IRR1DKSR0101", null, null, null, null, "دكوثرح1" },
                    { "IRR1DLGM0101", null, null, null, null, "دلقماح1" },
                    { "IRR1DMOR0101", null, null, null, null, "غدشتح1" },
                    { "IRR1DMVN0101", null, null, null, null, "كدماح1" },
                    { "IRR1DODE0101", null, null, null, null, "شدوصح1" },
                    { "IRR1DOSE0101", null, null, null, null, "داسوهح1" },
                    { "IRR1DPAK0101", null, null, null, null, "داروح1" },
                    { "IRR1DRKH0101", null, null, null, null, "پدرخشح1" },
                    { "IRR1DRZK0101", null, null, null, null, "درازكح1" },
                    { "IRR1DSIN0101", null, null, null, null, "دسيناح1" },
                    { "IRR1DSOB0101", null, null, null, null, "دسبحاح1" },
                    { "IRR1DZAH0101", null, null, null, null, "دزهراويح1" },
                    { "IRR1EPRS0101", null, null, null, null, "رتاپح1" },
                    { "IRR1EXIR0101", null, null, null, null, "دلرح1" },
                    { "IRR1FAIR0101", null, null, null, null, "فولاژح1" },
                    { "IRR1FAJR0101", null, null, null, null, "فجرح1" },
                    { "IRR1FIBR0101", null, null, null, null, "چفيبرح1" },
                    { "IRR1FKAS0101", null, null, null, null, "فخاسح1" },
                    { "IRR1FKHZ0101", null, null, null, null, "فخوزح1" },
                    { "IRR1FNAR0101", null, null, null, null, "خزرح1" },
                    { "IRR1FOLD0101", null, null, null, null, "فولادح1" },
                    { "IRR1FRIS0101", null, null, null, null, "فروسح1" },
                    { "IRR1FRVR0101", null, null, null, null, "فرآورح1" },
                    { "IRR1FTIR0101", null, null, null, null, "دفراح1" },
                    { "IRR1GBEH0101", null, null, null, null, "وصناح1" },
                    { "IRR1GCOZ0101", null, null, null, null, "غگلح1" },
                    { "IRR1GDIR0101", null, null, null, null, "وغديرح1" },
                    { "IRR1GESF0101", null, null, null, null, "قصفهاح1" },
                    { "IRR1GGAZ0101", null, null, null, null, "قزوينح1" },
                    { "IRR1GHAT0101", null, null, null, null, "ختوقاح1" },
                    { "IRR1GHEG0101", null, null, null, null, "قهكمتح1" },
                    { "IRR1GHND0101", null, null, null, null, "قشهدح1" },
                    { "IRR1GLOR0101", null, null, null, null, "قلرستح1" },
                    { "IRR1GMEL0101", null, null, null, null, "ومليح1" },
                    { "IRR1GMRO0101", null, null, null, null, "قمروح1" },
                    { "IRR1GNBO0101", null, null, null, null, "قنيشاح1" },
                    { "IRR1GORJ0101", null, null, null, null, "غگرجيح1" },
                    { "IRR1GOST0101", null, null, null, null, "خگسترح1" },
                    { "IRR1GPSH0101", null, null, null, null, "قپيراح1" },
                    { "IRR1GSBE0101", null, null, null, null, "قثابتح1" },
                    { "IRR1GSKE0101", null, null, null, null, "تكشاح1" },
                    { "IRR1GTSH0101", null, null, null, null, "شگلح1" },
                    { "IRR1HJPT0101", null, null, null, null, "حپتروح1" },
                    { "IRR1HMRZ0101", null, null, null, null, "همراهح1" },
                    { "IRR1HSHM0101", null, null, null, null, "حفاريح1" },
                    { "IRR1HTOK0101", null, null, null, null, "حتوكاح1" },
                    { "IRR1IAGM0101", null, null, null, null, "مرقامح1" },
                    { "IRR1IDOC0101", null, null, null, null, "واعتبارح1" },
                    { "IRR1IKCO0101", null, null, null, null, "خودروح1" },
                    { "IRR1IKHR0101", null, null, null, null, "وخارزمح1" },
                    { "IRR1INDM0101", null, null, null, null, "خكمكح1" },
                    { "IRR1INFO0101", null, null, null, null, "رانفورح1" },
                    { "IRR1JAMD0101", null, null, null, null, "فجامح1" },
                    { "IRR1JOSH0101", null, null, null, null, "بكابح1" },
                    { "IRR1KALZ0101", null, null, null, null, "بالبرح1" },
                    { "IRR1KDPS0101", null, null, null, null, "غدامح1" },
                    { "IRR1KFAN0101", null, null, null, null, "خفنرح1" },
                    { "IRR1KGND0101", null, null, null, null, "بكامح1" },
                    { "IRR1KHAZ0101", null, null, null, null, "لخزرح1" },
                    { "IRR1KHFZ0101", null, null, null, null, "كحافظح1" },
                    { "IRR1KHOC0101", null, null, null, null, "سخوزح1" },
                    { "IRR1KHSH0101", null, null, null, null, "خشرقح1" },
                    { "IRR1KIMI0101", null, null, null, null, "دكيميح1" },
                    { "IRR1KLBR0101", null, null, null, null, "غالبرح1" },
                    { "IRR1KNRZ0101", null, null, null, null, "كنورح1" },
                    { "IRR1KPRS0101", null, null, null, null, "كپارسح1" },
                    { "IRR1KRAF0101", null, null, null, null, "وكارح1" },
                    { "IRR1KRIR0101", null, null, null, null, "خكارح1" },
                    { "IRR1KRTI0101", null, null, null, null, "چكارنح1" },
                    { "IRR1KSAD0101", null, null, null, null, "كسعديح1" },
                    { "IRR1KSIM0101", null, null, null, null, "فاسمينح1" },
                    { "IRR1KSKA0101", null, null, null, null, "چكاوهح1" },
                    { "IRR1KVEH0101", null, null, null, null, "كاوهح1" },
                    { "IRR1LAMI0101", null, null, null, null, "فلاميح1" },
                    { "IRR1LAPS0101", null, null, null, null, "بشهابح1" },
                    { "IRR1LEAB0101", null, null, null, null, "شلعابح1" },
                    { "IRR1LENT0101", null, null, null, null, "خلنتح1" },
                    { "IRR1LKGH0101", null, null, null, null, "ولغدرح1" },
                    { "IRR1LMIR0101", null, null, null, null, "فلولهح1" },
                    { "IRR1LPAK0101", null, null, null, null, "غپاكح1" },
                    { "IRR1LSMD0101", null, null, null, null, "ولصنمح1" },
                    { "IRR1LZIN0101", null, null, null, null, "وليزح1" },
                    { "IRR1MADN0101", null, null, null, null, "ومعادنح1" },
                    { "IRR1MAGS0101", null, null, null, null, "زمگساح1" },
                    { "IRR1MAPN0101", null, null, null, null, "رمپناح1" },
                    { "IRR1MARK0101", null, null, null, null, "فاراكح1" },
                    { "IRR1MESI0101", null, null, null, null, "خوسازح1" },
                    { "IRR1MHKM0101", null, null, null, null, "خمهرح1" },
                    { "IRR1MINO0101", null, null, null, null, "غپينوح1" },
                    { "IRR1MKBT0101", null, null, null, null, "اخابرح1" },
                    { "IRR1MNGZ0101", null, null, null, null, "كمنگنزح1" },
                    { "IRR1MNSR0101", null, null, null, null, "خنصيرح1" },
                    { "IRR1MOTJ0101", null, null, null, null, "بموتوح1" },
                    { "IRR1MRGN0101", null, null, null, null, "غمارگح1" },
                    { "IRR1MRIN0101", null, null, null, null, "نمرينوح1" },
                    { "IRR1MSKN0101", null, null, null, null, "ثمسكنح1" },
                    { "IRR1MSMI0101", null, null, null, null, "فمليح1" },
                    { "IRR1MSTI0101", null, null, null, null, "خموتورح1" },
                    { "IRR1NAFT0101", null, null, null, null, "ونفتح1" },
                    { "IRR1NALM0101", null, null, null, null, "فنوالح1" },
                    { "IRR1NASI0101", null, null, null, null, "كفراح1" },
                    { "IRR1NBEH0101", null, null, null, null, "شبهرنح1" },
                    { "IRR1NGFO0101", null, null, null, null, "فنوردح1" },
                    { "IRR1NIKI0101", null, null, null, null, "ونيكيح1" },
                    { "IRR1NIRO0101", null, null, null, null, "بنيروح1" },
                    { "IRR1NKOL0101", null, null, null, null, "شكلرح1" },
                    { "IRR1NMOH0101", null, null, null, null, "خمحركهح1" },
                    { "IRR1NOSH0101", null, null, null, null, "غنوشح1" },
                    { "IRR1NOVN0101", null, null, null, null, "ونوينح1" },
                    { "IRR1NPRS0101", null, null, null, null, "شنفتح1" },
                    { "IRR1NSAZ0101", null, null, null, null, "كاذرح1" },
                    { "IRR1NSPS0101", null, null, null, null, "كفپارسح1" },
                    { "IRR1NSTH0101", null, null, null, null, "ثنوساح1" },
                    { "IRR1OFOG0101", null, null, null, null, "افقح1" },
                    { "IRR1OFRS0101", null, null, null, null, "ثفارسح1" },
                    { "IRR1OFST0101", null, null, null, null, "چافستح1" },
                    { "IRR1OIMC0101", null, null, null, null, "واميدح1" },
                    { "IRR1OMID0101", null, null, null, null, "اميدح1" },
                    { "IRR1PAKS0101", null, null, null, null, "شپاكساح1" },
                    { "IRR1PARK0101", null, null, null, null, "شاراكح1" },
                    { "IRR1PASH0101", null, null, null, null, "پاكشوح1" },
                    { "IRR1PASN0101", null, null, null, null, "پارسانح1" },
                    { "IRR1PELC0101", null, null, null, null, "لپارسح1" },
                    { "IRR1PETR0101", null, null, null, null, "وپتروح1" },
                    { "IRR1PFAN0101", null, null, null, null, "شفنح1" },
                    { "IRR1PIAZ0101", null, null, null, null, "غاذرح1" },
                    { "IRR1PIRN0101", null, null, null, null, "تپمپيح1" },
                    { "IRR1PJMZ0101", null, null, null, null, "جمح1" },
                    { "IRR1PKER0101", null, null, null, null, "كرماشاح1" },
                    { "IRR1PKHA0101", null, null, null, null, "شخاركح1" },
                    { "IRR1PKOD0101", null, null, null, null, "خپارسح1" },
                    { "IRR1PLKK0101", null, null, null, null, "پلاسكح1" },
                    { "IRR1PMSZ0101", null, null, null, null, "ثشرقح1" },
                    { "IRR1PNES0101", null, null, null, null, "شپناح1" },
                    { "IRR1PNTB0101", null, null, null, null, "شبريزح1" },
                    { "IRR1PRDZ0101", null, null, null, null, "شپديسح1" },
                    { "IRR1PRKT0101", null, null, null, null, "پرداختح1" },
                    { "IRR1PSER0101", null, null, null, null, "كسرامح1" },
                    { "IRR1PSHZ0101", null, null, null, null, "شيرازح1" },
                    { "IRR1PSIR0101", null, null, null, null, "كپشيرح1" },
                    { "IRR1PTAP0101", null, null, null, null, "تاپيكوح1" },
                    { "IRR1RADI0101", null, null, null, null, "ختورح1" },
                    { "IRR1RENA0101", null, null, null, null, "ورناح1" },
                    { "IRR1RIIR0101", null, null, null, null, "خريختح1" },
                    { "IRR1RINM0101", null, null, null, null, "خرينگح1" },
                    { "IRR1RKSH0101", null, null, null, null, "ركيشح1" },
                    { "IRR1ROOI0101", null, null, null, null, "كرويح1" },
                    { "IRR1ROZD0101", null, null, null, null, "دروزح1" },
                    { "IRR1RSAP0101", null, null, null, null, "ولساپاح1" },
                    { "IRR1RTIR0101", null, null, null, null, "ختراكح1" },
                    { "IRR1SADB0101", null, null, null, null, "ساربيلح1" },
                    { "IRR1SADR0101", null, null, null, null, "تاصيكوح1" },
                    { "IRR1SAHD0101", null, null, null, null, "ثشاهدح1" },
                    { "IRR1SAKH0101", null, null, null, null, "وساختح1" },
                    { "IRR1SAMA0101", null, null, null, null, "فاماح1" },
                    { "IRR1SAND0101", null, null, null, null, "وصندوقح1" },
                    { "IRR1SBAH0101", null, null, null, null, "وبهمنح1" },
                    { "IRR1SBEH0101", null, null, null, null, "غبشهرح1" },
                    { "IRR1SBHN0101", null, null, null, null, "سبهانح1" },
                    { "IRR1SBOJ0101", null, null, null, null, "سبجنوح1" },
                    { "IRR1SDAB0101", null, null, null, null, "سارابح1" },
                    { "IRR1SDOR0101", null, null, null, null, "سدورح1" },
                    { "IRR1SDST0101", null, null, null, null, "سدشتح1" },
                    { "IRR1SEFH0101", null, null, null, null, "سصفهاح1" },
                    { "IRR1SEIL0101", null, null, null, null, "سيلامح1" },
                    { "IRR1SEPA0101", null, null, null, null, "فسپاح1" },
                    { "IRR1SEPK0101", null, null, null, null, "سپح1" },
                    { "IRR1SFKZ0101", null, null, null, null, "سفارسح1" },
                    { "IRR1SFNO0101", null, null, null, null, "سفانوح1" },
                    { "IRR1SFRS0101", null, null, null, null, "سفارح1" },
                    { "IRR1SGAZ0101", null, null, null, null, "كگازح1" },
                    { "IRR1SGEN0101", null, null, null, null, "سقاينح1" },
                    { "IRR1SGOS0101", null, null, null, null, "ثامانح1" },
                    { "IRR1SHAD0101", null, null, null, null, "غشهدح1" },
                    { "IRR1SHFS0101", null, null, null, null, "شفارسح1" },
                    { "IRR1SHGN0101", null, null, null, null, "سهگمتح1" },
                    { "IRR1SHKR0101", null, null, null, null, "قشكرح1" },
                    { "IRR1SHMD0101", null, null, null, null, "كهمداح1" },
                    { "IRR1SHND0101", null, null, null, null, "پسهندح1" },
                    { "IRR1SHPZ0101", null, null, null, null, "غشاذرح1" },
                    { "IRR1SHSI0101", null, null, null, null, "شسيناح1" },
                    { "IRR1SHZG0101", null, null, null, null, "سهرمزح1" },
                    { "IRR1SINA0101", null, null, null, null, "كساوهح1" },
                    { "IRR1SIPA0101", null, null, null, null, "خساپاح1" },
                    { "IRR1SISH0101", null, null, null, null, "كساپاح1" },
                    { "IRR1SKAZ0101", null, null, null, null, "سخزرح1" },
                    { "IRR1SKBV0101", null, null, null, null, "وسكابح1" },
                    { "IRR1SKER0101", null, null, null, null, "سكرماح1" },
                    { "IRR1SKHS0101", null, null, null, null, "سخاشح1" },
                    { "IRR1SKOR0101", null, null, null, null, "سكردح1" },
                    { "IRR1SLMN0101", null, null, null, null, "غسالمح1" },
                    { "IRR1SMAZ0101", null, null, null, null, "سمازنح1" },
                    { "IRR1SNMA0101", null, null, null, null, "وصنعتح1" },
                    { "IRR1SORB0101", null, null, null, null, "فسربح1" },
                    { "IRR1SPAH0101", null, null, null, null, "وسپهح1" },
                    { "IRR1SPKH0101", null, null, null, null, "غشانح1" },
                    { "IRR1SPPE0101", null, null, null, null, "غشصفاح1" },
                    { "IRR1SPTA0101", null, null, null, null, "فپنتاح1" },
                    { "IRR1SRMA0101", null, null, null, null, "لسرماح1" },
                    { "IRR1SROD0101", null, null, null, null, "سرودح1" },
                    { "IRR1SSAP0101", null, null, null, null, "وساپاح1" },
                    { "IRR1SSEP0101", null, null, null, null, "سپاهاح1" },
                    { "IRR1SSHR0101", null, null, null, null, "سشرقح1" },
                    { "IRR1SSIN0101", null, null, null, null, "شيرانح1" },
                    { "IRR1SSOF0101", null, null, null, null, "سصوفيح1" },
                    { "IRR1STEH0101", null, null, null, null, "سترانح1" },
                    { "IRR1SURO0101", null, null, null, null, "سارومح1" },
                    { "IRR1SWIC0101", null, null, null, null, "بسويچح1" },
                    { "IRR1SZPO0101", null, null, null, null, "خپويشح1" },
                    { "IRR1TAIR0101", null, null, null, null, "پتايرح1" },
                    { "IRR1TAMI0101", null, null, null, null, "كماسهح1" },
                    { "IRR1TAYD0101", null, null, null, null, "حتايدح1" },
                    { "IRR1TAZB0101", null, null, null, null, "وآذرح1" },
                    { "IRR1TBAS0101", null, null, null, null, "كطبسح1" },
                    { "IRR1TGOS0101", null, null, null, null, "وتوسح1" },
                    { "IRR1TKNO0101", null, null, null, null, "تكنوح1" },
                    { "IRR1TKSM0101", null, null, null, null, "كترامح1" },
                    { "IRR1TMEL0101", null, null, null, null, "وتوسمح1" },
                    { "IRR1TMKH0101", null, null, null, null, "خمحورح1" },
                    { "IRR1TMLT0101", null, null, null, null, "تملتح1" },
                    { "IRR1TNOV0101", null, null, null, null, "تنوينح1" },
                    { "IRR1TOKA0101", null, null, null, null, "وتوكاح1" },
                    { "IRR1TOSA0101", null, null, null, null, "وتوصاح1" },
                    { "IRR1TRIR0101", null, null, null, null, "تايراح1" },
                    { "IRR1TRNS0101", null, null, null, null, "بترانسح1" },
                    { "IRR1TSAN0101", null, null, null, null, "امينح1" },
                    { "IRR1TSBE0101", null, null, null, null, "وبشهرح1" },
                    { "IRR1TSHE0101", null, null, null, null, "وتوشهح1" },
                    { "IRR1TSRZ0101", null, null, null, null, "كرازيح1" },
                    { "IRR1VSIN0101", null, null, null, null, "وسيناح1" },
                    { "IRR1YASA0101", null, null, null, null, "پاساح1" },
                    { "IRR1ZMYD0101", null, null, null, null, "خزامياح1" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Assets_InstrumentId",
                table: "Assets",
                column: "InstrumentId");

            migrationBuilder.CreateIndex(
                name: "IX_TradingData_InstrumentId",
                table: "TradingData",
                column: "InstrumentId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Assets");

            migrationBuilder.DropTable(
                name: "TradingData");

            migrationBuilder.DropTable(
                name: "Instruments");
        }
    }
}
